apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespaces.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
  - all-apps.yaml

## changes to config maps
patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yml
