#!/bin/bash

KIC_RES_EDGE_URL="http://localhost:32080"

PARENT_COMMAND=$(ps -o comm= $PPID)

usage() {
  echo "Usage: kic ${KIC_RES_EDGE_ENTITYNAME} ${PARENT_COMMAND} -i [id]"
  exit 1
}

if [ -z "${KIC_RES_EDGE_URL}" ]; then
  echo "Error: KIC_RES_EDGE_URL environment variable is not set"
fi

while getopts ":i:" opt; do
  case ${opt} in
    i )
      id="$OPTARG"
      ;;
    \? )
      usage
      ;;
  esac
done

if [ -z "$id" ]; then
  usage
fi

url="${KIC_RES_EDGE_URL}/api/v1/${KIC_RES_EDGE_ENTITYNAME}/${id}"
curl --silent --show-error "$url" | jq
