apiVersion: v1
kind: Service
metadata:
  name: imdb
  namespace: imdb
spec:
  ports:
  - name: http
    nodePort: 31080
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: imdb
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: imdb
  name: imdb
  namespace: imdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imdb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: imdb
    spec:
      containers:
      - args:
        - --in-memory
        - --region
        - central
        - --zone
        - central-tx
        image: ghcr.io/cse-labs/imdb:1.0.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 60
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 1024Mi
