apiVersion: v1
kind: Service
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
spec:
  selector:
    app: {{gitops.app}}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{gitops.port}}
      targetPort: {{gitops.port}}
