apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: {{gitops.cluster.gitopsBranch}}
  secretRef:
    name: flux-system
  url: https://github.com/{{gitops.cluster.gitopsRepo}}
