id: myapp
name: myapp
app: myapp
containerArgs: []
environment: dev
image: ghcr.io/cse-labs/myapp:latest
ingressPrefix: /
livenessProbe: /healthz
namespace: myapp
namespaceId: myapp
nodePort: 30080
port: 8080
readinessProbe: /readyz
targets: []
template: pib-service
