apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rea.namespace.name-redis-pvc
  namespace: rea.namespace.name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi
