apiVersion: v1
kind: Service
metadata:
  name: webv
  namespace: api
  labels:
    app: webv
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: webv
