apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: feature/770-add-kic-check
  secretRef:
    name: flux-system
  url: https://github.com/cse-labs/res-edge-labs
