#!/bin/bash

# "ds cicd" use the Res-Edge Automation docker image and the Res-Edge Data Service
# to generate GitOps manifest files for each Cluster

# Run "git status" to see the repo changes

# The changes are not pushed to GitHub
# use "ds deploy" to push any GitOps changes

echo "Running ci-cd locally ..."

docker run -it --rm \
  --net host \
  -v "$KIC_BASE":/goa \
  ghcr.io/cse-labs/res-edge-automation:0.9 \
  -s "${DS_URL}"
