#!/bin/bash

# Warning: this is a destructive command

# "ds reload" will reload the SQL database with the default sample data
# Any prior database changes will be overwritten and are not recoverable
# Use the --force flag to make the database changes

# get the pod name
pod=$(kubectl get pods -n res-edge | grep mssql | awk '{print $1}')

if [ "$pod" = "" ]; then
        echo "Unable to find mssql pod"
        exit 1
fi

# execute the load script "in" the pod
kubectl exec -n res-edge "$pod" -- /home/mssql/data/load.sh
