apiVersion: batch/v1
kind: Job
metadata:
 name: load-data
 namespace: res-edge
spec:
 template:
   metadata:
     name: load-data
     namespace: res-edge
   spec:
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 1001
      containers:
      - name: load-data
        image: ghcr.io/cse-labs/res-edge-sql:0.18
        imagePullPolicy: IfNotPresent
        command:
        - bash
        - -c
        - |
          cd data
          ./load.sh

        env:
          - name: MSSQL_NAME
            value: mssql
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: MSSQL_SA_PASSWORD
