#!/bin/bash

set -e

if [ -z "${KIC_DATASERVICE_URL}" ]; then
    echo "Error! Please set environment variable: KIC_DATASERVICE_URL";
    exit 1;
fi

function resedge_check {
    http "${KIC_DATASERVICE_URL}"/version
}

if ! resedge_check; then
    echo "ResEdge is not Running";
else
    echo "ResEdge is Running";
fi
