#!/bin/bash

cd "$REPO_BASE" || exit 1

if [ "$KIC_FULL_REPO" = "" ]; then
    echo "export KIC_FULL_REPO before running command"
    exit 1
fi

if [ "$KIC_PAT" = "" ]; then
    echo "export KIC_PAT before running command"
    exit 1
fi

if [ "$KIC_BRANCH" = "" ]; then
    echo "export KIC_BRANCH before running command"
    exit 1
fi

flux bootstrap git \
  --url "$KIC_FULL_REPO" \
  --branch "$KIC_BRANCH" \
  --token-auth \
  --password "$KIC_PAT" \
  --path "/clusters/central-la-nola-2301"
