#!/bin/bash

cd "$REPO_BASE" || exit 1

if [ "$KIC_FULL_REPO" = "" ]; then
    echo "export KIC_FULL_REPO before running command"
    exit 1
fi

if [ "$KIC_PAT" = "" ]; then
    echo "export KIC_PAT before running command"
    exit 1
fi

if [ "$KIC_BRANCH" = "" ]; then
    echo "export KIC_BRANCH before running command"
    exit 1
fi

cd deploy/flux || exit 1

kubectl apply -f components.yaml

flux create secret git flux-system -n flux-system --url "$KIC_FULL_REPO" -u gitops -p "$KIC_PAT"

kubectl apply -f source.yaml
kubectl apply -f kustomization-flux.yaml
