apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- argocd.yaml
#- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.5/manifests/install.yaml
- all-apps.yaml

## changes to config maps
patches:
- path: argocd-cmd-params-cm-patch.yaml
- path: nodeport-patch.yaml
