apiVersion: v1
kind: Service
metadata:
  name: tabs-spaces
  namespace: tabs-spaces
spec:
  ports:
  - name: http
    nodePort: 32088
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: tabs-spaces
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tabs-spaces
  name: tabs-spaces
  namespace: tabs-spaces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tabs-spaces
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tabs-spaces
    spec:
      containers:
      - env:
        - name: REGION
          value: west
        - name: ZONE
          value: west-ca
        - name: TITLE
          value: Can we still be friends?
        - name: KEY1
          value: Tabs
        - name: KEY2
          value: Spaces
        image: ghcr.io/cse-labs/go-vote:0.2.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 60
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 400m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
