apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.app}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: {{gitops.app}}
  template:
    metadata:
      labels:
        app: {{gitops.app}}
    spec:
      containers:
        - name: app
          image: {{gitops.image}}
          imagePullPolicy: Always
          args: {{gitops.containerArgs}}
          ports:
            - name: http
              containerPort: {{gitops.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{gitops.livenessProbe}}
              port: http
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: {{gitops.readinessProbe}}
              port: http
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 60
          resources:
            limits:
              cpu: {{gitops.cpuLimit}}
              memory: {{gitops.memoryLimit}}
            requests:
              cpu: {{gitops.cpuRequest}}
              memory: {{gitops.memoryRequest}}
