apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
  annotations:
    kubernetes.io/ingress.class: contour
    ingress.kubernetes.io/force-ssl-redirect: "false"

spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{gitops.ingressPrefix}}
        backend:
          service:
            name: {{gitops.app}}
            port:
              number: {{gitops.port}}
