#!/bin/bash

echo "Running integration tests on the cluster with failing requests (400 and 404)"

#!/bin/bash

docker run --net host --rm \
    ghcr.io/cse-labs/res-edge-webv:0.14 \
    --server "${DS_URL}" \
    --log-format TsvMin \
    --timeout 5 \
    --region Dev \
    --zone Dev \
    --tag Dev \
    --max-errors 10 \
    --summary Tsv \
    --verbose \
    --files integration.json
