apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/east-ga-atl-2302/flux-system/listeners
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
