apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    expression: none

resources:
  # - pvc.yaml
  # - redis.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
