apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    expression: none

resources:
  - service.yaml
  - deployment.yaml

images:
- name: ghcr.io/cse-labs/imdb
  newTag: 1.0.0
