#!/bin/bash

git pull
git clone https://github.com/retaildevcrews/pib-dotnet-webapi "$APP_LOWER"
cd "$APP_LOWER" || exit 1

# checkout the branch if specified
if [ "$KIC_APP_BRANCH" != "" ] && [ "$KIC_APP_BRANCH" != "main" ]; then
  git checkout $KIC_APP_BRANCH
  git pull
fi

# remove unused files
rm -rf .devcontainer
rm -rf .git
rm -rf .github
rm -f .gitignore
rm -f LICENSE
rm -f curl.sh
rm -f README.md

# move docs/readme if exists
if [ -f docs/README.md ]; then
    mv docs/README.md .
fi

# rename project
mv src/csapp.csproj "src/$APP_LOWER.csproj"

# replace CSApp and csapp
find . -type f -exec sed -i "s|\$PIB_BASE/csapp|$PWD|g" {} \;
find . -type f -exec sed -i "s|apps/csapp/|apps/$APP_LOWER/|g" {} \;

if [ "$KIC_APP_URL_PREFIX" = "" ]; then
  find . -type f -exec sed -i "s|/csapp/|/|g" {} \;
  find src -type f -exec sed -i "s|/csapp|/|g" {} \;
  find src -type f -exec sed -i "s|csapp/||g" {} \;
  find src -type f -exec sed  -i "s|c.RoutePrefix = \"csapp\"|c.RoutePrefix = string.Empty|g" {} \;
else
  find . -type f -exec sed -i "s|/csapp/|/$KIC_APP_URL_PREFIX/|g" {} \;
  find src -type f -exec sed -i "s|/csapp|/$KIC_APP_URL_PREFIX|g" {} \;
  find src -type f -exec sed -i "s|csapp/|$KIC_APP_URL_PREFIX/|g" {} \;
  find src -type f -exec sed  -i "s|c.RoutePrefix = \"csapp\"|c.RoutePrefix = \"$KIC_APP_URL_PREFIX\"|g" {} \;
  find kic-deploy/app/webv -type f -exec sed -i "s|          - --run-loop|          - --run-loop\n          - --url-prefix\n          - $KIC_APP_URL_PREFIX|g" {} \;
  find . -type f -exec sed -i "s|urlprefix: \"\"|urlprefix: /$KIC_APP_URL_PREFIX|g" {} \;
fi

find . -type f -exec sed -i "s/CSApp/$APP_NAME/g" {} \;
find . -type f -exec sed -i "s/csapp/$APP_LOWER/g" {} \;
find . -type f -exec sed -i "s|\$PIB_GHCR|$PIB_GHCR|g" {} \;
find . -type f -exec sed -i "s|{{repo}}|$PIB_REPO|g" {} \;
find . -type f -exec sed -i "s|{{branch}}|$PIB_BRANCH|g" {} \;
find . -type f -exec sed -i "s|{{nodePort}}|$KIC_APP_NODE_PORT|g" {} \;

if [ -d src/wwwroot ]; then
  cd src/wwwroot || exit 1

  if [ "$KIC_APP_URL_PREFIX" == "" ]; then
    mv csapp/* .
    rm -rf csapp
  else
    mv csapp "$KIC_APP_URL_PREFIX"
  fi

  cd ../..
fi

dotnet restore src

#git pull
#git add ..
#git commit -m "added $1"
#git push
