#!/bin/bash

PARENT_COMMAND=$(ps -o comm= $PPID)

if [ -z "${DS_URL}" ]; then
  echo "Error: DS_URL environment variable is not set"
  exit 1
fi

usage() {
  echo

  if [ "${KIC_RES_EDGE_ENTITYNAME}" = "groups" ]; then
    echo "Usage: kic ${KIC_RES_EDGE_ENTITYNAME} ${PARENT_COMMAND} [--search 'search term'] [--order-by id | name | path]"
  else
    echo "Usage: kic ${KIC_RES_EDGE_ENTITYNAME} ${PARENT_COMMAND} [--search 'search term'] [--order-by id | name]"
  fi

  if [ "${KIC_RES_EDGE_ENTITYNAME}" = "clusters" ]; then
    echo "   or: kic ${KIC_RES_EDGE_ENTITYNAME} ${PARENT_COMMAND} --group id | path"
    echo '   --group:  filter clusters by group'
  fi

  echo "   --search: Search ${KIC_RES_EDGE_ENTITYNAME} by name, metadata or tag (optional)"

  if [ "${KIC_RES_EDGE_ENTITYNAME}" = "groups" ]; then
    echo '   --order-by: id | name | path (default: id)'
  else
    echo '   --order-by: id | name (default: id)'
  fi

  echo

  exit 1
}

list() {
  # handle clusters --group
  if [ -n "${GROUP}" ]; then
    response=$(curl --silent --show-error "$URL" | jq -r '(.[] | [.id, .name]) | @tsv')
    echo "$response" | column -t -s $'\t' -N Id,Name -R Id -o '   '

  # handle groups (3 columns)
  elif [ "${KIC_RES_EDGE_ENTITYNAME}" = "groups" ]; then
    response=$(curl --silent --show-error "$URL" | jq -r '(.value[] | [.id, .name, .namePath]) | @tsv')
    echo "$response" | column -t -s $'\t' -N Id,Name,Path -R Id -o '   '

  # handle everything else
  else
    response=$(curl --silent --show-error "$URL" | jq -r '(.value[] | [.id, .name]) | @tsv')
    echo "$response" | column -t -s $'\t' -N Id,Name -R Id -o '   '
  fi
}

for arg in "$@"; do
  case $arg in
    --search)
      set -- "${@/$arg/-s}"
      ;;
    --order-by)
      set -- "${@/$arg/-o}"
      ;;
    --group)
      if [ "${KIC_RES_EDGE_ENTITYNAME}" = "clusters" ]; then
        set -- "${@/$arg/-g}"
      else
        echo
        echo "Error: --group is not a valid parameter"
        echo
        usage
      fi
      ;;
  esac
done

while getopts ":s:o:g:" f; do
    case "${f}" in
        s)
            SEARCH=$OPTARG ;;
        o)
            ORDERBY=$OPTARG ;;
        g)
            GROUP=$OPTARG ;;
        *)
            usage ;;
    esac
done

shift $((OPTIND-1))

# validate --order-by param
if [ "$KIC_RES_EDGE_ENTITYNAME" = "groups" ]; then
  if [ "$KIC_RES_EDGE_ENTITYNAME" = "groups" ] && [ -n "$ORDERBY" ] && [ "$ORDERBY" != "id" ] && [ "$ORDERBY" != "name" ] && [ "$ORDERBY" != "path" ]; then
    echo
    echo "Error: Order by supports either 'id' 'name' or 'path'"
    usage
  fi
elif [ -n "$ORDERBY" ] && [ "$ORDERBY" != "id" ] && [ "$ORDERBY" != "name" ]; then
  echo
  echo "Error: Order by supports either 'id' or 'name'"
  usage
fi

# base URL
KIC_BASE_URL="${DS_URL}/api/v1/${KIC_RES_EDGE_ENTITYNAME}/"

# add params if present
URL_PARAMS=()

if [ -n "${SEARCH}" ]; then
  URL_PARAMS+=("search=%22$SEARCH%22")
fi

if [ -n "${ORDERBY}" ]; then
  if [ "$ORDERBY" = "path" ]; then
    URL_PARAMS+=("orderby=namePath")
  else
    URL_PARAMS+=("orderby=${ORDERBY}")
  fi
fi

if [ -n "${GROUP}" ]; then
  if [ -n "${SEARCH}" ] || [ -n "${ORDERBY}" ]; then
      usage;
  fi

  KIC_BASE_URL+="group/${GROUP}"
fi

# Implode the array with the separator "&" to create a single string
URL_QUERY_STRING=$(printf "&%s" "${URL_PARAMS[@]}")
URL_QUERY_STRING=${URL_QUERY_STRING:1}

URL="${KIC_BASE_URL}"

if [ "$URL_QUERY_STRING" != "" ]; then
  URL+="?${URL_QUERY_STRING}"
fi

if ! list; then
  echo
  echo "Error: Failed to retrieve data from $URL"
  echo "Please check that the Res-Edge server is up and running with: kic check resedge"
  echo

  exit 1
fi
