apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dogs-cats-redis-pvc
  namespace: dogs-cats
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-csi
