apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
spec:
  selector:
    app.kubernetes.io/name: argocd-server

  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 32089
  type: NodePort
