apiVersion: v1
kind: Service
metadata:
  name: dogs-cats
  namespace: dogs-cats
spec:
  ports:
  - name: http
    nodePort: 31088
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: dogs-cats
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dogs-cats
  name: dogs-cats
  namespace: dogs-cats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogs-cats
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dogs-cats
    spec:
      containers:
      - env:
        - name: REGION
          value: west
        - name: ZONE
          value: west-ca
        - name: TITLE
          value: Dogz RULE!
        - name: KEY1
          value: Dogs
        - name: KEY2
          value: Cats
        image: ghcr.io/cse-labs/go-vote:0.2.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 60
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 400m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
