#!/bin/bash

set -e

function print_usage {
  echo "Usage: kic clusters --group <name>"
}

function get_clusters {
    curl -s http://localhost:32080/api/v1/groups?filter=name%20eq%20%27"$GROUP"%27&select=clustersTree
}

function list_clusters {

    CLUSTERS=$(get_clusters | jq -r ' .value[] | .clustersTree' )

    if [ "$CLUSTERS" = "" ]; then
        echo "No clusters found";
        exit 1;
    fi

    CLUSTERS=${CLUSTERS:1}
    CLUSTERS=${CLUSTERS::-1}

    for s in $(echo $CLUSTERS | sed "s/,/\n/g"); do echo $s | sed "s/\/api/localhost:32080\/api/g" | xargs curl -s | jq -r .name; done
}

GROUP=""
CLUSTERS=""

#read the options
TEMP=$(getopt -o 'n' --long group: -- "$@")
eval set -- "$TEMP"

# extract options and their arguments into variables.
while true ; do
    case "${1}" in
        -n|--group)
            GROUP=$2 ; shift 1 ;;
        --) shift ; break ;;
        *) list_clusters ; exit 1 ;;
    esac
done

if [ -z "${GROUP}" ]
then
    echo "Error: --group parameter is required";
    print_usage
    exit 1;
fi
