#!/bin/bash

KIC_RES_EDGE_URL="http://localhost:32080"
KIC_RES_EDGE_URL="https://api.res-edge.net"

URL_FILTER=""
URL_ORDER_BY=""

usage() {
  echo "Usage: $0 --search [name] --order-by [name/id]"
  exit 1
}

if [ -z "${KIC_RES_EDGE_URL}" ]; then
  echo "Error: KIC_RES_EDGE_URL environment variable is not set"
  usage
fi

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    --name)
        NAME="$2" shift 2 ;;
    --order-by)
        ORDERBY="$3" ; shift 2 ;;
    --) shift ; break ;;
    *) usage ;;
  esac
done

url="${KIC_RES_EDGE_URL}/api/v1/${KIC_RES_EDGE_ENTITYNAME}"

if [ "${NAME}" != "" ]; then
    URL_FILTER="\?filter=name%20eq%20%27"$NAME"%27"
fi

if [ "${ORDERBY}" != "" ]; then
    URL_ORDER_BY="\?orderby=$ORDERBY"
fi

# url="${url}${URL_FILTER}${URL_ORDER_BY}"
echo $url
echo $URL_FILTER
echo $URL_ORDER_BY
# curl "$url" | jq -r ' .value[] | .name'
