#!/bin/bash

usage() {
  echo "Usage: $0 --id [number]"
  exit 1
}

while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    --id)
      id="$2"
      shift
      shift
      ;;
    *)
      usage
      ;;
  esac
done

if [ -z "$id" ]; then
  usage
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
KIC_RES_EDGE_ENTITYNAME="policies" "$SCRIPT_DIR/entity-show" --id "$id"
