#!/bin/bash

# imports bootstrap
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPT_DIR/bootstrap

KIC_RES_EDGE_ENTITYNAME="policies" "$SCRIPT_DIR/entity-show" --id "$id"
