apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- listeners/kustomization-heartbeat.yaml
- listeners/kustomization-namespaces.yaml
- listeners/kustomization-redis.yaml
