###
# Resedge applications commands
###

commands:
- name: applications
  short: ResEdge applications commands
  scriptCommands:
  - name: show
    short: Show application metadata
    path: applications/show
  - name: list
    short: Search and list applications
    path: applications/list
