###
# Resedge applications commands
###

commands:
- name: applications
  short: ResEdge Applications commands
  scriptCommands:
  - name: show
    short: Show Applications information
    path: applications/show
  - name: list
    short: Search and list Applications
    path: applications/list
