apiVersion: k3d.io/v1alpha4
kind: Simple
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
metadata: {}
network: k3d
options:
  k3d:
    disableImageVolume: false
    disableLoadbalancer: false
    disableRollback: false
    loadbalancer: {}
    timeout: "60s"
    wait: true
  k3s:
    extraArgs:
    - arg: --tls-san=127.0.0.1
      nodeFilters:
      - server:*
  kubeconfig:
    switchCurrentContext: true
    updateDefaultKubeconfig: true
  runtime:
    HostPidMode: false
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
- port: 8080:8080
  nodeFilters:
  - loadbalancer
- port: 8088:8088
  nodeFilters:
  - loadbalancer
- port: 1433:1433
  nodeFilters:
  - loadbalancer
- port: 3000:3000
  nodeFilters:
  - loadbalancer
- port: 9090:9090
  nodeFilters:
  - loadbalancer
registries: {}
servers: 1
volumes:
- nodeFilters:
  - server:0
  volume: $KIC_BASE/gitopsrepo:/gitopsrepo
