apiVersion: k3d.io/v1alpha4
kind: Simple
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
metadata: {}
network: k3d
options:
  k3d:
    disableImageVolume: false
    disableLoadbalancer: false
    disableRollback: false
    loadbalancer: {}
    timeout: "60s"
    wait: true
  k3s:
    extraArgs:
    - arg: --tls-san=127.0.0.1
      nodeFilters:
      - server:*
  kubeconfig:
    switchCurrentContext: true
    updateDefaultKubeconfig: true
  runtime:
    HostPidMode: false
ports:
- nodeFilters:
  - server:0
  port: 30000:30000
- nodeFilters:
  - server:0
  port: 30080-30089:30080-30089
- nodeFilters:
  - server:0
  port: 31080-31089:31080-31089
- nodeFilters:
  - server:0
  port: 31433:31433
- nodeFilters:
  - server:0
  port: 32000:32000
- nodeFilters:
  - server:0
  port: 32080-32089:32080-32089
- nodeFilters:
  - server:0
  port: 32101-32199:32101-32199
registries: {}
servers: 1
volumes:
- nodeFilters:
  - server:0
  volume: /prometheus:/prometheus
- nodeFilters:
  - server:0
  volume: /grafana:/grafana
