#!/bin/bash

function webv_check {
    kubectl exec -it jumpbox -- http webv.api.svc.cluster.local:8080/version
}


if ! webv_check; then
    echo "WebV is not Running";
else
    echo "WebV is Running";
fi
