apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
- argocd.yaml
#- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.5/manifests/install.yaml
- naas.yaml

## changes to config maps and NodePort
patches:
- path: argo-cmd-params-cm-patch.yaml
- path: argo-server-svc-patch.yaml
