kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql
  namespace: res-edge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
