apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - fluentbit/account.yaml
  - fluentbit/daemonset.yaml
  - fluentbit/log.yaml
  - fluentbit/stdout-config.yaml
  - prometheus/pvc.yaml
  - prometheus/clusterRole.yaml
  - prometheus/config-map.yaml
  - prometheus/deployment.yaml
  - grafana/pvc.yaml
  - grafana/dashboard-provider.yaml
  - grafana/datasource.yaml
  - grafana/deployment.yaml
  - grafana/dashboards/app.yaml
  - grafana/dashboards/dotnet.yaml
