app: heartbeat
containerArgs: []
cpuLimit: 100m
cpuRequest: 100m
environment: dev
image: ghcr.io/cse-labs/heartbeat:latest
ingressPrefix: /heartbeat
livenessProbe: /healthz
memoryLimit: 64Mi
memoryRequest: 64Mi
namespace: heartbeat
port: 8080
readinessProbe: /readyz
targets:
    - all
template: pib-service
