#!/bin/bash

set -e

dir=""
app="apps/$1"

if [ "$app" = "apps/" ]; then
    echo "app directory not found";
    exit 1;
fi

if [ "$2" = "" ]; then
    echo "Usage: kic overlay name"
    exit 1;
fi

# change to the apps/myapp dir
cd "$app";

# select the environment
if [ -d "kustomize/dev" ]; then dir="kustomize/dev"; fi
if [ -d "kustomize/test" ]; then dir="kustomize/test"; fi
if [ -d "kustomize/prod" ]; then dir="kustomize/prod"; fi

if [ "$dir" = "" ]; then
    echo "Kustomize directory not found";
    exit 1;
fi

if [ -d "$dir/overlays/$2" ]; then
    echo "Overlay $2 already exists";
    exit 1;
fi

mkdir -p "$dir/overlays/$2"

cat <<EOF > "$dir/overlays/$2/kustomization.yaml"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    version: $2
    clusters: none
resources:
- ../../base

images:
- name: $(cat $dir/base/deployment.yaml|grep image: | cut -d ':' -f 2)
  newTag: $2
EOF

code "$dir/overlays/$2/kustomization.yaml"
