#!/bin/bash

set -e

dir=""
app="apps/$2"

if [ "$app" = "apps/" ]; then
    echo "app directory not found";
    exit 1;
fi

if [ "$1" = "" ]; then
    echo "Usage: kic overlay name"
    exit 1;
fi

# change to the apps/myapp dir
cd "$app";

# select the environment
if [ -d "kustomize/dev" ]; then dir="kustomize/dev"; fi
if [ -d "kustomize/test" ]; then dir="kustomize/test"; fi
if [ -d "kustomize/prod" ]; then dir="kustomize/prod"; fi

if [ "$dir" = "" ]; then
    echo "Kustomize directory not found";
    exit 1;
fi

if [ -d "$dir/overlays/$1" ]; then
    echo "Overlay $1 already exists";
    exit 1;
fi

mkdir -p "$dir/overlays/$1"

cp "$dir/base/kustomization.yaml" "$dir/overlays/$1/kustomization.yaml"

code "$dir/overlays/$1/kustomization.yaml"
