#!/bin/bash

set -e

dir=""

if [ "$1" = "" ]; then
    echo "Usage: kic overlay name"
    exit 1;
fi

# change to the apps/imdb dir
# todo - imdb shoud be a param
if [ -d "apps/imdb" ]; then cd apps/imdb; fi

# select the environment
if [ -d "kustomize/dev" ]; then dir="kustomize/dev"; fi
if [ -d "kustomize/test" ]; then dir="kustomize/test"; fi
if [ -d "kustomize/prod" ]; then dir="kustomize/prod"; fi

if [ "$dir" = "" ]; then
    echo "Kustomize directory not found";
    exit 1;
fi

if [ -d "$dir/overlays/$1" ]; then
    echo "Overlay $1 already exists";
    exit 1;
fi

mkdir -p "$dir/overlays/$1"

cat <<EOF > "$dir/overlays/$1/kustomization.yaml"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    version: $1
    clusters: none

resources:
- ../../base

# todo - read the image name from the base yaml
images:
- name: ghcr.io/bartr/imdb
  newTag: $1
EOF

code "$dir/overlays/$1/kustomization.yaml"
