apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.app}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: {{gitops.app}}
  template:
    metadata:
      labels:
        app: {{gitops.app}}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: {{gitops.app}}
          image: {{gitops.image}}
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          livenessProbe:
            httpGet:
              path: {{gitops.livenessProbe}}
              port: http
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: {{gitops.readinessProbe}}
              port: http
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 60
          resources:
            limits:
              cpu: {{gitops.cpuLimit}}
              memory: {{gitops.memoryLimit}}
            requests:
              cpu: {{gitops.cpuRequest}}
              memory: {{gitops.memoryRequest}}
