apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{gitops.app}}-ingress
  namespace: imdb
spec:
  virtualhost:
    fqdn: {{ist.cluster.store.res-edge.com}}
    tls:
      secretName: {{gitops.app}}
  includes:
    - name: {{gitops.app}}
      namespace: {{gitops.namespace}}
