apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    clusters: central, east, west

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
- name: ghcr.io/bartr/imdb
  newTag: 1.0.0
