apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: flux-system
  url: https://github.com/cse-labs/res-edge-labs
  ref:
    branch: gitops-lab
