apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: ist.cluster.gitops-branch
  secretRef:
    name: flux-system
  url: ist.cluster.gitops-repo
