---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/joaquinrz-tx-atx-0001/ingress-nginx/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
