---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/joaquinrz-tx-atx-0001/cert-manager/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
