apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - crd.yaml
  - security.yaml
  - config.yaml
  - services.yaml
  - network.yaml
  - deployment.yaml
